/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tcl_tbrowser3_NativeClass */

#ifndef _Included_com_tcl_tbrowser3_NativeClass
#define _Included_com_tcl_tbrowser3_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tcl_tbrowser3_NativeClass
 * Method:    tbrowserLoadUrlWithName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tcl_tbrowser3_NativeClass_tbrowserLoadUrlWithName
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_tcl_tbrowser3_NativeClass
 * Method:    tbrowserPushKeyEventWithName
 * Signature: (Ljava/lang/String;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tcl_tbrowser3_NativeClass_tbrowserPushKeyEventWithName
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     com_tcl_tbrowser3_NativeClass
 * Method:    tbrowserDestoryWithName
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tcl_tbrowser3_NativeClass_tbrowserDestoryWithName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tcl_tbrowser3_NativeClass
 * Method:    tbrowserSetVisible
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tcl_tbrowser3_NativeClass_tbrowserSetVisible
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_tcl_tbrowser3_NativeClass
 * Method:    tbrowserSetActive
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tcl_tbrowser3_NativeClass_tbrowserSetActive
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
