/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wenwen1zhang_myapp_NativeClass */

#ifndef _Included_com_example_wenwen1zhang_myapp_NativeClass
#define _Included_com_example_wenwen1zhang_myapp_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wenwen1zhang_myapp_NativeClass
 * Method:    getServiceFromJNI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_wenwen1zhang_myapp_NativeClass_getServiceFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
